"""empty message

Revision ID: b21721a5a871
Revises: 
Create Date: 2019-04-24 16:09:17.528374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b21721a5a871'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('thread', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('thread', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('thread', sa.Column('thread_hash', sa.String(length=64), nullable=True))
    op.drop_column('thread', 'thread_name')
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created')
    op.add_column('thread', sa.Column('thread_name', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('thread', 'thread_hash')
    op.drop_column('thread', 'name')
    op.drop_column('thread', 'created')
    op.drop_column('message', 'created')
    # ### end Alembic commands ###
