"""empty message

Revision ID: f7317da4ed25
Revises: 9dc7a8244890
Create Date: 2019-08-06 00:23:32.005979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7317da4ed25'
down_revision = '9dc7a8244890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('thread_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'thread', ['thread_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'thread_id')
    op.drop_column('message', 'sender_id')
    # ### end Alembic commands ###
