

export const mockUsers = {
    1:{
        id:1,
        username:'testuser1'
    },
    2:{
        id:2,
        username:'testuser2'
    },
    3:{
        id:3,
        username:'testuser3'
    },
    4:{
        id:4,
        username:'testuser4'
    },
    5:{
        id:5,
        username:'testuser5'
    }
}

export const mockThreads = {
    0:{
        id:0,
        name:'mockthread1',
        users:[1,2],
        messages:[1,2,3,4,12]
    },
    1:{
        id:1,
        name:'mockthread2',
        users:[2,3],
        messages:[5,6,7]
    },
    2:{
        id:2,
        name:'mockthread3',
        users:[4,5],
        messages:[8,9,10,11]
    }
}


export const mockMessages = {
    1:{
        id:1,
        sender:1,
        content:'test'
    },
    2:{
        id:2,
        sender:2,
        content:'test2'
    },
    3:{
        id:3,
        sender:1,
        content:'test3'
    },
    4:{
        id:4,
        sender:2,
        content:'test4'
    },
    5:{
        id:5,
        sender:3,
        content:'test5'
    },
    6:{
        id:6,
        sender:2,
        content:"test6"
    },
    7:{
        id:7,
        sender:3,
        content:'test7'
    },
    8:{
        id:8,
        sender:4,
        content:'test8'
    },
    9:{
        id:9,
        sender:5,
        content:'test9'
    },
    10:{
        id:10,
        sender:5,
        content:'test10'
    },
    11:{
        id:11,
        sender:4,
        content:"test11"
    },
    12:{
        id:12,
        sender:1,
        content:'test12'
    }
}

