export const INITIALIZE_GAMESTATE = "INITIALIZE_GAMESTATE";
export const UPDATE_GAMESTATE = "UPDATE_GAMESTATE";
export const PLAYER_KEYED = "PLAYER_KEYED";
export const ADD_INVENTORY_ITEM = "ADD_INVENTORY_ITEM";
export const REMOVE_INVENTORY_ITEM = "REMOVE_INVENTORY_ITEM";