export const LOAD_STARTED = "LOAD_STARTED";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAILED =  "LOAD_FAILED";
export const START_INITIAL_LOAD = "START_INITIAL_LOAD";
export const INITIAL_LOAD_FINISHED = "INITIAL_LOAD_FINISHED"
export const ASSET_LINK = "ASSET_LINK";
export default {LOAD_FAILED,LOAD_SUCCESS,LOAD_STARTED, START_INITIAL_LOAD, INITIAL_LOAD_FINISHED}