// ActionTypes for messaging
export const SEND_MESSAGE = "SEND_MESSAGE";
export const RECIEVE_MESSAGE = "RECIEVE_MESSAGE";
export const REPORT_MESSAGE_READ = "REPORT_MESSAGE_READ";
export const REPORT_MESSAGE_RECIEVED = "REPORT_MESSAGE_RECIEVED";
export const JOIN_THREAD_REQUESTED = "JOIN_THREAD_REQUEST";
export const REQUEST_NEW_THREAD = "REQUEST_NEW_THREAD";
export const NEW_THREAD_FAILED = "NEW_THREAD_FAILED";

// User List Actions
export const USER_LIST_RECIEVED = "USER_LIST_RECIEVED";
export const USER_JOINED = "USER_JOINED";
export const USER_LEFT = "USER_LEFT";

// Messaging UI Action Types
export const NEW_THREAD_ACCEPTED = "NEW_THREAD_ACCEPTED";
export const THREAD_OPENED = "THREAD_OPENED";
export const THREAD_CLOSED = "THREAD_CLOSED";
export const CREATE_NEW_THREAD = "CREATE_NEW_THREAD";
export const NEW_THREAD_CLOSED = "NEW_THREAD_CLOSED";
export const USER_ADDED_TO_THREAD = "USER_ADDED_TO_THREAD";
export const CLOSE_ALL_THREADS = "CLOSE_ALL_THREADS";
export const ACTIVE_THREAD_CHANGED = "ACTIVE_THREAD_CHANGED";
export const NAVIGATE_LEFT = "NAVIGATE_LEFT";
export const NAVIGATE_RIGHT = "NAVIGATE_RIGHT";

export const MESSAGE_HAS_FAILED = "MESSAGE_FAILED";
export const MESSAGE_WAS_RECIEVED = "MESSAGE_RECIEVED";
export const MESSAGE_WAS_READ = "MESSAGE_READ";
