// ActionTypes for messaging
export const SEND_MESSAGE = "SEND_MESSAGE";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const NEW_MESSAGE = "NEW_MESSAGE"
export const MESSAGE_HAS_FAILED = "MESSAGE_FAILED";
export const MESSAGE_WAS_RECIEVED = "MESSAGE_RECIEVED";
export const MESSAGE_WAS_READ = "MESSAGE_READ";
export const REPORT_MESSAGE_READ = "REPORT_MESSAGE_READ";
export const REPORT_MESSAGE_RECIEVED = "REPORT_MESSAGE_RECIEVED";
export const USER_JOINED = "USER_JOINED";
export const USER_LEFT = "USER_LEFT";
export const USER_LIST_RECIEVED = "USER_LIST_RECIEVED";
export const JOIN_THREAD_REQUESTED = "JOIN_THREAD_REQUEST";
export const REQUEST_NEW_THREAD = "REQUEST_NEW_THREAD";
export const NEW_THREAD_FAILED = "NEW_THREAD_FAILED";
