export const MOVE_PLAYER = "MOVE_PLAYER";
export const MOVE_PLAYER_FAILED = "MOVE_PLAYER_FAILED";
export const MOVE_PLAYER_SUCCESS = "MOVE_PLAYER_SUCCESS";


export default {MOVE_PLAYER,MOVE_PLAYER_FAILED,MOVE_PLAYER_SUCCESS};