export const CREATE_SOCKET = "CREATE_SOCKET";
export const SOCKET_CREATED = "SOCKET_CREATED";
export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_FAILED = "SOCKET_FAILED";;
export const CLOSE_SOCKET = "CLOSE_SOCKET";
export const SOCKET_CLOSED = "SOCKET_CLOSED";
export const SOCKET_CLOSE_DELAYED = "SOCKET_CLOSE_DELAYED";